import { View } from 'react-native'
import Modal from 'react-native-modal'

import Title from '../../../../components/title'
import Button from '../../../../components/button'
import Info from '../../../../components/info'

function TrainingDetailsModal({ isOpen, close, coachFirstName, coachLastName, date, start, finish, room, capacity, level, title, regime, exercises, wrapperStyle, headerWrapperStyle, titleTextStyle, exitButtonWrapperStyle, exitButtonTextStyle, dataRowWrapperStyle, dataWrapperStyle, dataPropertyTextStyle, dataValueTextStyle }) {
    return (
        <Modal
            isVisible={isOpen}
            backdropOpacity={1}
        >
            <View
                style={wrapperStyle}
            >
                <View
                    style={headerWrapperStyle}
                >
                    <Title
                        text='training details'
                        textStyle={titleTextStyle}
                    />
                    <Button
                        loading={false}
                        showMessage={false}
                        messageText={null}
                        work={close}
                        buttonText='close'
                        wrapperStyle={null}
                        buttonWrapperStyle={exitButtonWrapperStyle}
                        buttonTextStyle={exitButtonTextStyle}
                        messageWrapperStyle={null}
                        messageTextStyle={null}
                    />
                </View>
                <View>
                    <View
                        style={dataRowWrapperStyle}
                    >
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='coach'
                                value={coachFirstName + ' ' + coachLastName}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='date'
                                value={date}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                    </View>
                    <View
                        style={dataRowWrapperStyle}
                    >
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='start'
                                value={start}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='finish'
                                value={finish}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                    </View>
                    <View
                        style={dataRowWrapperStyle}
                    >
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='room'
                                value={room}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='capacity'
                                value={capacity}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                    </View>
                    <View
                        style={dataRowWrapperStyle}
                    >
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='level'
                                value={level}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='title'
                                value={title}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                    </View>
                    <View
                        style={dataRowWrapperStyle}
                    >
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='regime'
                                value={regime}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                        <View
                            style={dataWrapperStyle}
                        >
                            <Info
                                property='exercises'
                                value={exercises}
                                propertyTextStyle={dataPropertyTextStyle}
                                valueTextStyle={dataValueTextStyle}
                            />
                        </View>
                    </View>
                </View>
            </View>
        </Modal>
    )
}

export default TrainingDetailsModal